// src/plannerRouter.ts
import express from 'express';
import { google } from 'googleapis';
import { GoogleGenAI, Type } from '@google/genai';
import { v4 as uuidv4 } from 'uuid';
import { Plan, Step } from './src/types/planner';

const router = express.Router();

router.post('/generate', async (req, res) => {
  try {
    const { goal } = req.body;
    if (!goal || goal.trim().length < 5) {
      return res.status(400).json({ success: false, error: 'Strategic goal description is too short.' });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ success: false, error: 'Gemini API is not configured on the server.' });
    }

    const ai = new GoogleGenAI({ apiKey });

    const responseSchema = {
      type: Type.OBJECT,
      properties: {
        goal_summary: {
          type: Type.STRING,
          description: "A short, 4-8 word concise active-verb summary of the strategic goal."
        },
        steps: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              action: {
                type: Type.STRING,
                description: "An actionable, clear, singular task, action, or micro-habit step."
              },
              frequency: {
                type: Type.STRING,
                enum: ["daily", "weekly", "monthly", "one-time"],
                description: "The ideal recurrence frequency for performing this step."
              },
              duration_minutes: {
                type: Type.INTEGER,
                description: "Recommended session duration in minutes (between 5 and 180)."
              }
            },
            required: ["action", "frequency", "duration_minutes"]
          },
          description: "A chronological list of 3 to 5 clear action steps towards achieving the goal."
        }
      },
      required: ["goal_summary", "steps"]
    };

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `Break down the following goal into a highly actionable sequence of micro-tasks or habit steps that are practical to track: "${goal}"`,
      config: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
        temperature: 0.2
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error('No suggestions generated by the AI model.');
    }

    const parsed = JSON.parse(text);
    const plan: Plan = {
      id: uuidv4(),
      goal_summary: parsed.goal_summary || goal.slice(0, 50),
      steps: parsed.steps.map((s: any) => ({
        id: uuidv4(),
        action: s.action,
        frequency: s.frequency || 'daily',
        duration_minutes: s.duration_minutes || 15,
        completed: false,
      })),
      status: 'active',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    res.json({ success: true, plan });
  } catch (error: any) {
    console.error('Action planner generation error:', error);
    res.status(500).json({ success: false, error: error.message || 'Failed to formulate strategic blueprint.' });
  }
});

router.post('/confirm', async (req, res) => {
  try {
    const { plan } = req.body;
    if (!plan || !plan.steps) {
      return res.status(400).json({ success: false, error: 'Strategic plan content is missing.' });
    }

    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ success: false, error: 'Google Account access token is missing.' });
    }
    const token = authHeader.split(' ')[1];

    // Initialize Google API clients
    const auth = new google.auth.OAuth2();
    auth.setCredentials({ access_token: token });

    const calendar = google.calendar({ version: 'v3', auth });
    const tasks = google.tasks({ version: 'v1', auth });
    const gmail = google.gmail({ version: 'v1', auth });

    // Step 1: Resolve Task List inside Google Tasks
    let listId: string | null = null;
    try {
      const taskLists = await tasks.tasklists.list();
      listId = taskLists.data.items?.find(l => l.title === 'CodeMind Strategic Plans')?.id || null;
      
      if (!listId) {
        const newList = await tasks.tasklists.insert({
          requestBody: { title: 'CodeMind Strategic Plans' }
        });
        listId = newList.data.id || null;
      }
    } catch (taskErr) {
      console.error('Error resolving Google Tasks list:', taskErr);
    }

    const updatedSteps: Step[] = [];

    // Step 2: Iterate and create events + tasks
    for (const step of plan.steps) {
      const startTime = new Date();
      startTime.setDate(startTime.getDate() + 1); // Scheduled starting tomorrow
      startTime.setHours(9, 0, 0, 0); // default slot is 9 AM

      const endTime = new Date(startTime.getTime() + (step.duration_minutes || 15) * 60 * 1000);

      // Define Recurrence Rules for Calendar
      const recurrenceRule = step.frequency === 'daily'
        ? ['RRULE:FREQ=DAILY;COUNT=7'] // Daily for 1 week
        : step.frequency === 'weekly'
        ? ['RRULE:FREQ=WEEKLY;COUNT=4'] // Weekly for 1 month
        : step.frequency === 'monthly'
        ? ['RRULE:FREQ=MONTHLY;COUNT=3'] // Monthly for 3 months
        : undefined;

      // Add to Google Calendar
      let googleEventId: string | undefined;
      try {
        const calEvent = await calendar.events.insert({
          calendarId: 'primary',
          requestBody: {
            summary: `🎯 ${step.action}`,
            description: `Scheduled action for strategic plan: "${plan.goal_summary}". Crafted by CodeMind Assistant.`,
            start: { dateTime: startTime.toISOString(), timeZone: 'UTC' },
            end: { dateTime: endTime.toISOString(), timeZone: 'UTC' },
            recurrence: recurrenceRule,
            reminders: {
              useDefault: false,
              overrides: [
                { method: 'popup', minutes: 15 },
                { method: 'email', minutes: 120 }
              ]
            }
          }
        });
        googleEventId = calEvent.data.id || undefined;
      } catch (calErr) {
        console.error(`Calendar insertion failed for step: ${step.action}`, calErr);
      }

      // Add to Google Tasks
      let googleTaskId: string | undefined;
      if (listId) {
        try {
          const createdTask = await tasks.tasks.insert({
            tasklist: listId,
            requestBody: {
              title: `🎯 ${step.action}`,
              notes: `Goal: ${plan.goal_summary}\nFrequency: ${step.frequency}\nDuration: ${step.duration_minutes}m`,
              due: startTime.toISOString()
            }
          });
          googleTaskId = createdTask.data.id || undefined;
        } catch (taskInsertErr) {
          console.error(`Tasks insertion failed for step: ${step.action}`, taskInsertErr);
        }
      }

      updatedSteps.push({
        ...step,
        google_event_id: googleEventId,
        google_task_id: googleTaskId,
        completed: false
      });
    }

    // Step 3: Send confirmation summary via Gmail API
    try {
      const emailHtml = `
      <div style="font-family: 'Inter', -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px; border: 2px solid #e2e8f0; border-radius: 24px; background-color: #ffffff; color: #1e293b;">
        <div style="border-bottom: 2px solid #10b981; padding-bottom: 16px; margin-bottom: 24px;">
          <h2 style="color: #10b981; font-weight: 700; margin: 0; font-size: 24px;">Strategic Goal Deployed!</h2>
          <p style="color: #64748b; font-size: 14px; margin: 4px 0 0 0;">CodeMind strategic roadmap tracker</p>
        </div>
        
        <p style="font-size: 16px; line-height: 1.6; color: #334155;">
          Hello! Your brand new strategic plan for <strong>"${plan.goal_summary}"</strong> has been successfully configured and deployed to your Google Workspace.
        </p>
        
        <div style="background-color: #f8fafc; border-radius: 16px; padding: 20px; border: 1px solid #f1f5f9; margin: 24px 0;">
          <h3 style="color: #0f172a; margin-top: 0; font-size: 16px; font-weight: 600;">📋 Deployed Action Items:</h3>
          <ul style="padding-left: 0; list-style-type: none; margin: 0;">
            ${updatedSteps.map((step, idx) => `
              <li style="margin-bottom: 14px; padding-left: 28px; position: relative;">
                <span style="position: absolute; left: 0; color: #10b981; font-weight: bold;">${idx + 1}.</span>
                <strong style="color: #0f172a; display: block; font-size: 14px;">${step.action}</strong>
                <span style="font-size: 12px; color: #64748b; display: block; margin-top: 2px;">
                  ⏱️ ${step.duration_minutes} minutes | 📅 Recurrence: ${step.frequency}
                </span>
              </li>
            `).join('')}
          </ul>
        </div>
        
        <p style="font-size: 14px; line-height: 1.5; color: #475569;">
          We have automatically set up recurring calendar events to remind you of these habits starting tomorrow at 9 AM, and added them to your Tasks.
        </p>
        
        <hr style="border: none; border-top: 1px dashed #cbd5e1; margin: 28px 0;" />
        <p style="font-size: 11px; color: #94a3b8; text-align: center; margin-bottom: 0;">
          This automatic strategy dispatch was powered by CodeMind Assistant &reg;
        </p>
      </div>
      `;

      const emailLines = [
        `To: me`,
        `Subject: 🎯 Strategic Roadmap Deployed: "${plan.goal_summary}"`,
        'Content-Type: text/html; charset="utf-8"',
        '',
        emailHtml
      ].join('\n');

      const encodedEmail = Buffer.from(emailLines)
        .toString('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');

      await gmail.users.messages.send({
        userId: 'me',
        requestBody: {
          raw: encodedEmail
        }
      });
      console.log('Roadmap email summary sent.');
    } catch (gmailErr) {
      console.error('Gmail summary notification failed:', gmailErr);
    }

    const updatedPlan: Plan = {
      ...plan,
      steps: updatedSteps,
      status: 'active',
      updated_at: new Date().toISOString()
    };

    res.json({ success: true, plan: updatedPlan });
  } catch (error: any) {
    console.error('Action planner deployment error:', error);
    res.status(500).json({ success: false, error: error.message || 'Failed to synchronize with Google Workspace.' });
  }
});

export default router;
